### PR TITLE
New UI: April 25th, 2015

### PR DESCRIPTION
**Pull request by gnaseri**
Here is our new Mobile UI.

### CODE REVIEW

**Comment by Rezar** [comment]
Is it resolved ? I see some email but I am not sure if it has been done yet.

**Comment by manouriz** [comment]
Hi Reza,
I had a quick look at repository and in last 13 hours she did some correct
commits. But about a pull request I couldnt do anything more from git
website. It has a conflict and should be merge manually.
I dont know git very well but I can suggest her to install git GUI (
https://windows.github.com/) and then she can do a merge very easy.
I have to go work now and I cant access my computer until night late.
We can have a teamviewer session too tomorrow.

Best
Manouchehr

**Comment by gnaseri** [comment]
Hi Reza and Manouchehr,
Thank you for your information.
I am closing the "Pull request" because we don't need it anymore. I "merged" the new UI changes directly from a clone of "insight" into it.

**Comment by manouriz** [comment]
Hi,
Yes, I tested it.
Everything is now ok and it works properly.

best,
Manouchehr

**Comment by Rezar** [comment]
thanks a lot

**Pull request closed without merging**
